### ISSUE TITLE
Build fails while generating thumbnails

### ISSUE THREAD

**Issue by schleiftier** [voidlabs/versafix-template#16]
Hi, 
when trying to build the template using the provided script by running `npm run-script build`, it fails with the following error:

`ReferenceError: cmd is not defined
    at makeThumbs (/home/frederic/XR/versafix-template/src/makeThumbs.js:23:64)`

The reason is that in line 5 of `src/makeThumbs.js` the variable `phantombin` is assigned the property `path` of `require(phantomjs-prebuilt)`, which exists, but is `null`. This of course does not work when trying to run that variable as part of a shell command `var result = cp.execSync(phantombin + ' ' + args.join(' '), { stdio: [0, 1, 2] });` in line 19.

My environment is as follows:

- OS: Ubuntu 19.10
- nodejs v12.14.1
- npm 6.13.4

Any idea what I am doing wrong? Is my node version to new? Is phantombin not installed in the correct version?

Thanks,
Frederic

**Comment by bago** [comment]
Sounds like you have issues with the phantomjs-prebuild module. path is null when it fails:
https://github.com/Medium/phantomjs/blob/master/lib/phantomjs.js#L20

Have a look here: https://github.com/Medium/phantomjs/issues/747

**Comment by schleiftier** [comment]
Seems you are right. I checked if the phantomjs binary was actually downloaded - it was not. 
Running `npm install` in a fresh clone installed the binary correctly and now the script completes as expected. 

Thanks for the hint!
