### ISSUE TITLE
Issue with Images - Blurry - Poor Resolution

### ISSUE THREAD

**Issue by themak1985** [voidlabs/versafix-template#18]
@bago Adding this here as the issue may effect just the versafix template.

It also seems that images used in templates are treated differently than in production emails. Attached you will see two of the same images, both on the triple block with text. The top image is what we had in the template, the bottom image, we added in the production email. the source is the same file.

![Screenshot_20200218-131359](https://user-images.githubusercontent.com/28904266/74765153-0b155f00-5251-11ea-837d-3722a35500f9.png)

**Comment by bago** [comment]
The 2 images don't have the same A/R, the second one is cut.
They don't seem 2 columns of the same block, instead looks like one is a column of a multicolumn block, while the other is a different block with a bigger desktop version image.

That said, I don't know how you change the HTML when you send it, so I can't tell anything more from this screenshot.

PS: don't tag me in posts, please.

**Comment by themak1985** [comment]
My apologies on the tag - that example was bad - attached is an email generated from mosaico.io,
the original picture we used. I think the challenge is on mobile screens - the resolution is just too small. it seems like it should reduce to double (or triple the size)

[email (2).zip](https://github.com/voidlabs/versafix-template/files/4226768/email.2.zip)

**Comment by francescbassas** [comment]
See the related discussion on veda-consulting/uk.co.vedaconsulting.mosaico#50
