### ISSUE TITLE
Outlook forwarding problem

### ISSUE THREAD

**Issue by nicolob** [voidlabs/versafix-template#19]
That's what happens when you try to forward an email.
![InkedEmailDuranteInoltro_LI](https://user-images.githubusercontent.com/56966379/84123251-dfa1c480-aa39-11ea-9a77-7664c319f566.jpg)

**Comment by bago** [comment]
Correctly rendering on most email clients is already a very complex task. We don't really care about the bugs email clients have during forwarding. So, this is an Outlook bug, one we decide to ignore (as it probably doesn't have a fix that does not require reducing the compatibility with other email clients).
